[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests"
]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
pythonpath = [
    "."
]

[tool.coverage.run]
branch = true
source = [
    "dataset_readers",
    "reader_utils",
    "data_models"
]

[tool.coverage.report]
show_missing = true
skip_covered = true